name: baseconvert
description: Convert any rational number from any (positive integer)
  base to any (positive integer) base. Output numbers as List or String.
version: 0.0.1
author: Alex Collette
homepage: hiddenquarter.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
